"""add title location and hourly_rate to freelancer_profile

Revision ID: 115461d67ab6
Revises: b8c68477d698
Create Date: 2026-03-19 04:39:48.124350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115461d67ab6'
down_revision = 'b8c68477d698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profiles', schema=None) as batch_op:
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('location')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
