"""Sync project columns

Revision ID: 2abe46b3dd3c
Revises: 115461d67ab6
Create Date: 2026-03-19 05:30:39.228794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abe46b3dd3c'
down_revision = '115461d67ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('budget_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proposals_count', sa.Integer(), nullable=True))
        batch_op.drop_column('budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('proposals_count')
        batch_op.drop_column('deadline')
        batch_op.drop_column('budget_max')
        batch_op.drop_column('budget_min')

    # ### end Alembic commands ###
