"""Add portfolio_links to freelancer profile

Revision ID: 90f99d6ac905
Revises: b7219e319256
Create Date: 2026-03-18 23:27:22.150293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f99d6ac905'
down_revision = 'b7219e319256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profiles', schema=None) as batch_op:
        batch_op.drop_column('portfolio_links')

    # ### end Alembic commands ###
