"""Add is_active to users

Revision ID: b8c68477d698
Revises: b7d08c0a2cbd
Create Date: 2026-03-19 03:29:18.231424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8c68477d698'
down_revision = 'b7d08c0a2cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('action_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_client_id', ['client_id'], unique=False)
        batch_op.create_index('ix_contracts_freelancer_id', ['freelancer_id'], unique=False)
        batch_op.create_index('ix_contracts_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_contracts_status', ['status'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index('ix_milestones_contract_id', ['contract_id'], unique=False)
        batch_op.create_index('ix_milestones_status', ['status'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index('ix_disputes_milestone_id', ['milestone_id'], unique=False)
        batch_op.create_index('ix_disputes_status', ['status'], unique=False)

    op.create_table('escrow_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_escrow_contract_id', ['contract_id'], unique=False)
        batch_op.create_index('ix_escrow_milestone_id', ['milestone_id'], unique=False)
        batch_op.create_index('ix_escrow_type', ['type'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_flagged')

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_escrow_type')
        batch_op.drop_index('ix_escrow_milestone_id')
        batch_op.drop_index('ix_escrow_contract_id')

    op.drop_table('escrow_transactions')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index('ix_disputes_status')
        batch_op.drop_index('ix_disputes_milestone_id')

    op.drop_table('disputes')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index('ix_milestones_status')
        batch_op.drop_index('ix_milestones_contract_id')

    op.drop_table('milestones')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_status')
        batch_op.drop_index('ix_contracts_project_id')
        batch_op.drop_index('ix_contracts_freelancer_id')
        batch_op.drop_index('ix_contracts_client_id')

    op.drop_table('contracts')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
